name: Publish resume in JSONResume format as a Github Page

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: checkout gh pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install resume & theme
        run: npm install -g resumed jsonresume-theme-macchiato

      - name: Build resume
        run: resumed --theme jsonresume-theme-macchiato

      - run: cp resume.html gh-pages/index.html

      - name: Commit and push HTML
        working-directory: gh-pages
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add -A
          git commit -m "Update gh-pages with new resume" || exit 0
          git push origin gh-pages
