name: Publish resume in JSONResume format as a Github Page

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: checkout gh pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: elegant
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: gh-pages/index.html

      - name: Sync files to pages branch
        # update with other files you want to sync
        run: |
          cp avatar.jpg gh-pages/avatar.jpg

      - name: Commit and push HTML
        working-directory: gh-pages
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add -A
          git commit -m "Update gh-pages with new report" || exit 0
          git push origin gh-pages
